Sprint-4
ClevertecFrontendLab/Veronika2811 pull request #4
Opened 2024-03-17 20:17 UTC by Veronika2811

Add Calendar Page

2024-03-17 20:20 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710706841/update-past-trainings-3_360x740.png)

2024-03-18 06:35 UTC, vvikota requested changes

2024-03-18 06:35 UTC, vvikota commented on src/components/AuthContainer/utils/fieldValidation/passwordValidationRules.ts
> +            if (!/^[a-zA-Z0-9]{8,}$/.test(value)) {
регулярку в констнату

2024-03-18 06:35 UTC, vvikota commented on src/components/BreadcrumbCustom/BreadcrumbCustom.tsx
> +    const removeActiveMenuKey = () => {
const removeActiveMenuKey = () => dispatch(setActiveMenuKey(''));

2024-03-18 10:32 UTC, ValadzkoAliaksei commented
#  Результаты тестов
Процент пройденных тестов: 100%.
Общее количество тестов: 4.
Количество непройденных тестов: 0.
***
**calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/calendar-page_1440x900.png)
***
**create-new-training-1_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/create-new-training-1_1440x900.png)
***
**create-new-training-2_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/create-new-training-2_1440x900.png)
***
**create-new-training-3_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/create-new-training-3_1440x900.png)
***
**empty-calendar-page_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/empty-calendar-page_1440x900.png)
***
**get-training-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/get-training-error_1440x900.png)
***
**get-training-list-error_1440x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/get-training-list-error_1440x900.png)
***
**update-future-trainings-1_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/update-future-trainings-1_833x900.png)
***
**update-future-trainings-2_833x900.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/update-future-trainings-2_833x900.png)
***
**update-future-trainings-3.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/update-future-trainings-3.png)
***
**update-past-trainings-1_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/update-past-trainings-1_360x740.png)
***
**update-past-trainings-2.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/update-past-trainings-2.png)
***
**update-past-trainings-3_360x740.png**
![Скриншот автотестов](https://static.clevertec.ru/media/sprint1/Veronika2811/1710757925/update-past-trainings-3_360x740.png)

2024-03-18 15:16 UTC, ValadzkoAliaksei approved these changes

2024-03-18 15:16 UTC, ValadzkoAliaksei commented on src/redux/selectors.ts
> +export const currentTrainingSelector = (state: RootState) => state.trainingSlice.currentTraining;
на каждый вздох делать свой селектор конечно не очень)
а если бы их было 100+?)
думаю тут бы помогла деструктуризация...

2024-03-18 19:02 UTC, vvikota approved these changes

2024-03-18 19:03 UTC, merged